remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

# Setup
title:  "Digital Activism at the University of Oregon"             
tagline: A Toolkit For Embracing Student Voices           
description: A multimedia essay focussed on the impact of digital activism on University of Oregon's campus        
url:     http://eng470-s23.github.io          
baseurl:   /jamieyanofskydemosight/            
