remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Setup
title:  "Digital Activism at the University of Oregon: A Toolkit For Embracing Student Voices"             
tagline:              
description: A Multimedia Essay focussed on the impact of Digital Activism on University of Oregon's campus and student body.          
url:     http://eng470-s23.github.io          
baseurl:   /demo-site/            
